apps/imoveis/urls.py
from django.urls import path

from . import views


app_name = 'imoveis'
urlpatterns = [
    path('', views.ImovelIndexView.as_view(), name='index'),
    path('add/', views.ImovelCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ImovelDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.ImovelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.ImovelDeleteView.as_view(), name='delete'),
]

finxi/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('imoveis/', include('apps.imoveis.urls', namespace='imoveis')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/addresses/models.py
from django.db import models
from django.utils.translation import gettext as _


class AbstractStreet(models.Model):
    country = models.CharField(_('country'), max_length=50)
    state = models.CharField(_('state'), max_length=50)
    city = models.CharField(_('city'), max_length=50)
    neighborhood = models.CharField(_('neighborhood'), max_length=50)
    street = models.CharField(_('street'), max_length=50)

    class Meta:
        abstract = True
        verbose_name = _('street')
        verbose_name_plural = _('streets')

    @property
    def neighborhood_full_name(self):
        return _('{neighborhood}, {city} - {state}').format(
            neighborhood=self.neighborhood,
            city=self.city,
            state=self.state,
            country=self.country,
        )

    @property
    def street_full_name(self):
        return _('{street} - {neighborhood}').format(
            street=self.street, neighborhood=self.neighborhood_full_name)


class AbstractAddressDetail(models.Model):
    postal_code = models.CharField(_('postal code'), max_length=20)
    number = models.CharField(_('number'), max_length=50)
    complement = models.CharField(
        _('complement'), max_length=50, null=True, blank=True)
    reference = models.CharField(
        _('reference'), max_length=100, null=True, blank=True)

    class Meta:
        abstract = True
        verbose_name = _('address')
        verbose_name_plural = _('addresses')

    @property
    def address_full_name(self):
        return _('{street}, {number} - {neighborhood}, {postal_code}').format(
            street=self.street,
            number=self.number,
            neighborhood=self.neighborhood_full_name,
            postal_code=self.postal_code,
        )


class AbstractAddress(AbstractStreet, AbstractAddressDetail):

    class Meta:
        abstract = True

    def __str__(self):
        return self.address_full_name


class AbstractAddressHistory(AbstractAddress):

    class Meta:
        abstract = True
        verbose_name = _('address history')
        verbose_name_plural = _('address history')

apps/imoveis/models.py
from django.db import models
from django.db.models.signals import post_save
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext as _

from apps.addresses.models import AbstractAddress


def photo_directory_path(instance, filename):
    import os
    import uuid

    filename = '{}.{}'.format(uuid.uuid4().hex, filename.split('.')[-1])
    return os.path.join('imoveis', filename)


class Imovel(AbstractAddress):
    quartos = models.PositiveSmallIntegerField(_('quartos'))
    suites = models.PositiveSmallIntegerField(
        _('suítes'), null=True, blank=True)
    vagas_garagem = models.PositiveSmallIntegerField(
        _('vagas de garagem'), null=True, blank=True)
    area_util = models.PositiveSmallIntegerField(_('área útil (M²)'))
    area_total = models.PositiveSmallIntegerField(
        _('área total (M²)'), null=True, blank=True)
    aluguel = models.DecimalField(
        _('aluguel'), max_digits=10, decimal_places=2)
    condominio = models.DecimalField(
        _('condomínio'), max_digits=10, decimal_places=2, null=True,
        blank=True)
    iptu = models.DecimalField(
        _('IPTU'), max_digits=10, decimal_places=2, null=True, blank=True)
    descricao = models.TextField(_('descrição'), null=True, blank=True)
    image = models.ImageField(_('image'), upload_to=photo_directory_path)
    thumbnail = models.ImageField(
        _('thumbnail'), upload_to=photo_directory_path, null=True,
        editable=False)

    class Meta:
        verbose_name = _('imóvel')
        verbose_name_plural = _('imóveis')

    def get_absolute_url(self):
        return reverse('imoveis:detail', kwargs={'pk': self.pk})


@receiver(pre_save, sender=Imovel)
def imovel_pre_save(sender, instance, *args, **kwargs):
    if instance.pk:
        old = Imovel.objects.get(pk=instance.pk)
        if old.image.url != instance.image.url:
            instance.thumbnail = None


@receiver(post_save, sender=Imovel)
def imovel_post_save(sender, instance, *args, **kwargs):
    from .tasks import create_thumbnail

    if not instance.thumbnail:
        create_thumbnail.delay(instance.pk)

apps/addresses/views.py
from django.shortcuts import render

# Create your views here.

apps/imoveis/views.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView


from .models import Imovel


class ImovelIndexView(ListView):
    model = Imovel

    def get_queryset(self):
        query = self.request.GET.get('q')
        if not query:
            return Imovel.objects.all()

        return Imovel.objects.filter(
            Q(city__search=query) |
            Q(neighborhood__search=query) |
            Q(street__search=query) |
            Q(postal_code__search=query)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context


class ImovelCreateView(CreateView):
    model = Imovel
    fields = '__all__'


class ImovelDetailView(DetailView):
    model = Imovel


class ImovelUpdateView(UpdateView):
    model = Imovel
    fields = '__all__'


class ImovelDeleteView(DeleteView):
    model = Imovel
    success_url = reverse_lazy('imoveis:index')

apps/imoveis/templates/imoveis/base.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <h2>{% trans "Properties" %}</h2>
    <a href="{% url 'imoveis:index' %}">{% trans "List all" %}</a>
    <a href="{% url 'imoveis:create' %}">{% trans "Add new" %}</a>
    {% block content %}{% endblock %}
</body>
</html>

apps/imoveis/templates/imoveis/imovel_confirm_delete.html
{% extends "imoveis/base.html" %}
{% load i18n %}


{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>{% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}</p>
        <input type="submit" value="{% trans 'Confirm' %}" />
    </form>
{% endblock %}

apps/imoveis/templates/imoveis/imovel_detail.html
{% extends "imoveis/base.html" %}
{% load i18n %}


{% block content %}
    <h1>{{ object }}</h1>

    {% if imovel.thumbnail %}
    <p><img src="{{ object.thumbnail.url }}" height="150" width="150"/></p>
    {% endif %}

    {% if object.quartos is not None %}
    <p>{% trans "Quartos" %}: {{ object.quartos }}</p>
    {% endif %}

    {% if object.vagas_garagem is not None %}
    <p>{% trans "Vagas de garagem" %}: {{ object.vagas_garagem }}</p>
    {% endif %}

    {% if object.area_util is not None %}
    <p>{% trans "Área útil (M²)" %}: {{ object.area_util }}</p>
    {% endif %}

    {% if object.area_total is not None %}
    <p>{% trans "Área total (M²)" %}: {{ object.area_total }}</p>
    {% endif %}

    {% if object.aluguel is not None %}
    <p>{% trans "Aluguel" %}: {{ object.aluguel }}</p>
    {% endif %}

    {% if object.condominio is not None %}
    <p>{% trans "Condomínio" %}: {{ object.condominio }}</p>
    {% endif %}

    {% if object.iptu is not None %}
    <p>{% trans "IPTU" %}: {{ object.iptu }}</p>
    {% endif %}

    {% if object.descricao %}
    <p>{% trans "Descrição" %}: {{ object.descricao }}</p>
    {% endif %}
{% endblock %}

apps/imoveis/templates/imoveis/imovel_form.html
{% extends "imoveis/base.html" %}
{% load i18n %}


{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Save' %}" />
    </form>
{% endblock %}

apps/imoveis/templates/imoveis/imovel_list.html
{% extends "imoveis/base.html" %}
{% load i18n %}


{% block content %}
    <form action="" method="get">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="{% trans 'Search' %}" />
    </form>

    <ul>
        {% for imovel in object_list %}
        <li>
            {% if imovel.thumbnail %}
            <img src="{{ imovel.thumbnail.url }}" height="150" width="150"/>
            {% endif %}

            {{ imovel }}
            <a href="{% url 'imoveis:detail' imovel.pk %}">{% trans "Detail" %}</a>
            <a href="{% url 'imoveis:update' imovel.pk %}">{% trans "Update" %}</a>
            <a href="{% url 'imoveis:delete' imovel.pk %}">{% trans "Delete" %}</a>
        </li>
        {% empty %}
        <li>{% trans "No properties yet." %}</li>
        {% endfor %}
    </ul>
{% endblock %}